### ISSUE TITLE
`riak_cs`  won't get `TERM` signal to stop gracefully

### ISSUE THREAD

**Issue by pataquets** [TI-Tokyo/riak_cs#10]
https://github.com/TI-Tokyo/riak_cs/blob/5b978a49de7b0263bc3a23efe7e7354c57926201/Dockerfile#L20

As per [CMD](https://docs.docker.com/engine/reference/builder/#cmd) documentation, this will wrap `riak_cs` process in a `sh` subprocess.
This would prevent [external signals from docker](https://docs.docker.com/engine/reference/commandline/kill/) from reaching `riak_cs` process. `docker stop` is basically doing a `docker kill -s TERM` graceful stop.

Since, `riak_cs foreground` should be always run, with optional command line switches, I would suggest to use [ENTRYPOINT](https://docs.docker.com/engine/reference/builder/#entrypoint) instead. Otherwise, as a lesser evil, at least use `CMD`'s _exec_ form.

I can submit a PR, if desired.

**Comment by hmmr** [comment]
The Dockerfile we provide is more of a "reference implementation", rather than an attempt to provide for real-world production cases. Some may want to build and run it on the latest OTP-25 or -26 while others may have reasons to stick with OTP-22. Some might even choose to install it from a package instead of building it inside a docker container. There's also an issue with configuring it: one can mount a dir with customized riak-cs.conf from their Dockerfile at runtime, or directly edit it as part of start-up command sequence ending with `riak-cs start`. We make no attempt to cover all bases here.

There is a sister project, https://github.com/TI-Tokyo/riak_cs_service_bundle, which you may find useful or inspiring.

That said, I will gladly review and accept your PR.

**Comment by pataquets** [comment]
Thanks for the quick answer and for all the useful info.
In fact, I wasn't aware of the bundle repo. I will check it out for sure.
I've sent the above mentioned PR. As a bonus, I've sent another PR which can account for the usage case you mention of customizing the Erlang version used in the build (see #12).
